### ISSUE TITLE
aws-deployment-framework-bootstrap-pipeline failed at UploadAndUpdateBaseStacks stage

### ISSUE THREAD

**Issue by singhpr** [awslabs/aws-deployment-framework#198]
I am getting below error, seem issue with some limit with parameter store

```
2019-12-06 10:10:39,310 | INFO | __main__ | ADF Log Level is INFO | (generate_pipelines.py:158) 
2019-12-06 10:10:39,324 | INFO | deployment_map | Loading deployment_map file deployment_map.yml | (deployment_map.py:55) 
Traceback (most recent call last): 
  File "/codebuild/output/src437114731/src/adf-build/python/parameter_store.py", line 32, in put_parameter 
    assert current_value == value 
AssertionError 
 
During handling of the above exception, another exception occurred: 
 
Traceback (most recent call last): 
  File "./adf-build/generate_pipelines.py", line 211, in <module> 
    main() 
  File "./adf-build/generate_pipelines.py", line 207, in main 
    thread.join() 
  File "/codebuild/output/src437114731/src/adf-build/python/thread.py", line 30, in join 
    raise self.exc 
  File "/codebuild/output/src437114731/src/adf-build/python/thread.py", line 22, in run 
    **self._kwargs 
  File "./adf-build/generate_pipelines.py", line 135, in worker_thread 
    deployment_map.update_deployment_parameters(pipeline) 
  File "/codebuild/output/src437114731/src/adf-build/deployment_map.py", line 41, in update_deployment_parameters 
    str(self.account_ou_names) 
  File "/codebuild/output/src437114731/src/adf-build/python/parameter_store.py", line 41, in put_parameter 
    Overwrite=True 
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call 
    return self._make_api_call(operation_name, kwargs) 
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 661, in _make_api_call 
    raise error_class(parsed_response, operation_name) 
botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the PutParameter operation: Standard tier parameters support a maximum parameter value of 4096 characters. To create a larger parameter value, upgrade the parameter to use the advanced-parameter tier. For more information, see https://docs.aws.amazon.com/systems-manager/latest/userguide/parameter-store-advanced-parameters.html

```

**Comment by bundyfx** [comment]
Hi @singhpr 

Thanks - This is indeed an issue in the current release due to the size of a pipeline, this will be resolved in the next release (3.0) by making this specific parameter use advanced tiering in Parameter Store.

**Comment by duduz** [comment]
@bundyfx this really affects us, I'm not sure that staying with Parameter Store will be the right way to go.
looking ahead, the limits of parameter store as a service. when you'll reach 2x the accounts you currently have, you might encounter this issue once more. even after increasing to the advanced tier and getting 8K.

my thoughts - there's 2 ways to properly solve this.
1. every time that a parameter is larger than 4K, adf will divide it into separate parameters.
2. Use DynamoDB, and then you're max item size will become 400K

**Comment by duduz** [comment]
@bundyfx  this really affects us, I'm not sure that staying with Parameter Store will be the right way to go.
looking ahead, when you'll reach 2x the accounts you currently have, you might encounter this issue once more. even after increasing to the advanced tier and getting 8K.

my thoughts - there's 2 ways to properly solve this.
1. every time that a parameter is larger than 4K, adf will divide it into separate parameters.
2. Use DynamoDB, and then you're max item size will become 400K

**Comment by bundyfx** [comment]
> @bundyfx this really affects us, I'm not sure that staying with Parameter Store will be the right way to go.
> looking ahead, when you'll reach 2x the accounts you currently have, you might encounter this issue once more. even after increasing to the advanced tier and getting 8K.
> 
> my thoughts - there's 2 ways to properly solve this.
> 
> 1. every time that a parameter is larger than 4K, adf will divide it into separate parameters.
> 2. Use DynamoDB, and then you're max item size will become 400K

Hi @duduz - yes, thanks for the input, we will be moving to s3 for storage of the state of the existing pipeline in the 3.0 release due shortly.
