### ISSUE TITLE
Cross-account role assumption of adf-readonly-automation-role fails

### ISSUE THREAD

**Issue by jcaxmacher** [awslabs/aws-deployment-framework#230]
From our Deployment account, we are seeing error messages like the following in the codebuild portion of our pipelines when it tries to resolve parameters from CloudFormation stacks in different accounts.

The `adf-readonly-automation-role` has a condition on the trust policy which only allows assumption from the codebuild role in the deployment account when the `aws:sourceArn` condition key has a matching codebuild project ARN from the deployment account.  When we remove this condition, everything works properly.  Is it possible that the `aws:sourceArn` condition key is not set when the `adf-build/generate_params.py` calls STS to assume the role?

```
[Container] 2020/01/28 16:25:19 Running command python adf-build/generate_params.py
--
21 | Traceback (most recent call last):
22 | File "adf-build/generate_params.py", line 166, in <module>
23 | main()
24 | File "adf-build/generate_params.py", line 162, in main
25 | parameters.create_parameter_files()
26 | File "adf-build/generate_params.py", line 83, in create_parameter_files
27 | compare_params
28 | File "adf-build/generate_params.py", line 148, in _param_updater
29 | self._determine_parameter_structure(comparison_parameters, resolver)
30 | File "adf-build/generate_params.py", line 135, in _determine_parameter_structure
31 | return self._determine_parameter_structure(value, resolver)
32 | File "adf-build/generate_params.py", line 136, in _determine_parameter_structure
33 | if self._determine_intrinsic_function(resolver, value, key):
34 | File "adf-build/generate_params.py", line 125, in _determine_intrinsic_function
35 | return resolver.fetch_stack_output(value, key)
36 | File "/codebuild/output/src169200121/src/adf-build/resolver.py", line 52, in fetch_stack_output
37 | 'importer'
38 | File "/codebuild/output/src169200121/src/adf-build/python/sts.py", line 25, in assume_cross_account_role
39 | RoleArn=role_arn, RoleSessionName=role_session_name
40 | File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call
41 | return self._make_api_call(operation_name, kwargs)
42 | File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 661, in _make_api_call
43 | raise error_class(parsed_response, operation_name)
44 | botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the AssumeRole operation: User: arn:aws:sts::XXXXXXXXXX:assumed-role/adf-codebuild-role/AWSCodeBuild-d23ea1b2-9849-4748-8c1e-8f12c9d029f9 is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::YYYYYYYYYYYY:role/adf-readonly-automation-role
```

**Comment by bundyfx** [comment]
Thanks @jcaxmacher - I will test this one out and ensure its working as intended for 3.0.5.
