### ISSUE TITLE
Adding new target region to adfconfig fails

### ISSUE THREAD

**Issue by hynynen** [awslabs/aws-deployment-framework#252]
So far we have been deploying all our resources to Europe, but now we wanted to create some WAF rules etc. for CloudFront, so we have to add us-east-1 as target region in adconfig.yml.

Git diff:
```
diff --git a/adfconfig.yml b/adfconfig.yml
index c6deb92..7c1b476 100644
--- a/adfconfig.yml
+++ b/adfconfig.yml
@@ -5,7 +5,6 @@ regions:
   deployment-account: eu-west-1 # The region you define as your main deployment region
   targets: # A list of regions you wish to bootstrap and also deploy into via pipelines
     - eu-west-1
+    - us-east-1
 config:
   main-notification-endpoint:
     - type: slack # slack or email
```
This results in an error in bootstrapping pipeline:
```
2020-03-11 11:22:12,017 \| ERROR \| __main__ \| 1111111111- Failed to update its base stack due to missing parameters (deployment_account_id or kms_arn), ensure this account has been bootstrapped correctly by being moved from the root into an Organizational Unit within AWS Organizations. \| (main.py:226)
--
173 | Traceback (most recent call last):
174 | File "/codebuild/output/src222872215/src/adf-build/shared/python/cloudformation.py", line 201, in _create_change_set
175 | ChangeSetType=self._get_change_set_type())
176 | File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 316, in _api_call
177 | return self._make_api_call(operation_name, kwargs)
178 | File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 626, in _make_api_call
179 | raise error_class(parsed_response, operation_name)
180 | botocore.exceptions.ClientError: An error occurred (ValidationError) when calling the CreateChangeSet operation: Unable to fetch parameters [organization_id] from parameter store for this account.
181 |  
182 | During handling of the above exception, another exception occurred:
183 |  
184 | Traceback (most recent call last):
185 | File "adf-build/main.py", line 218, in worker_thread
186 | cloudformation.create_stack()
187 | File "/codebuild/output/src222872215/src/adf-build/shared/python/cloudformation.py", line 277, in create_stack
188 | create_change_set = self._create_change_set()
189 | File "/codebuild/output/src222872215/src/adf-build/shared/python/cloudformation.py", line 206, in _create_change_set
190 | raise GenericAccountConfigureError(error)
191 | errors.GenericAccountConfigureError: An error occurred (ValidationError) when calling the CreateChangeSet operation: Unable to fetch parameters [organization_id] from parameter store for this account.
192 |  
193 | The above exception was the direct cause of the following exception:
194 |  
195 | Traceback (most recent call last):
196 | File "adf-build/main.py", line 348, in <module>
197 | main()
198 | File "adf-build/main.py", line 326, in main
199 | thread.join()
200 | File "/codebuild/output/src222872215/src/adf-build/shared/python/thread.py", line 30, in join
201 | raise self.exc
202 | File "/codebuild/output/src222872215/src/adf-build/shared/python/thread.py", line 22, in run
203 | **self._kwargs
204 | File "adf-build/main.py", line 227, in worker_thread
205 | raise Exception from error
206 | Exception
207 | 2020-03-11 11:22:12,605 \| ERROR \| __main__ \| 1111111111- Failed to update its base stack due to missing parameters (deployment_account_id or kms_arn), ensure this account has been bootstrapped correctly by being moved from the root into an Organizational Unit within AWS Organizations. \| (main.py:226)
208 | 2020-03-11 11:22:12,723 \| ERROR \| __main__ \| 22222222222- Failed to update its base stack due to missing parameters (deployment_account_id or kms_arn), ensure this account has been bootstrapped correctly by being moved from the root into an Organizational Unit within AWS Organizations. \| (main.py:226)
209 | 2020-03-11 11:22:12,835 \| ERROR \| __main__ \| 33333333333 - Failed to update its base stack due to missing parameters (deployment_account_id or kms_arn), ensure this account has been bootstrapped correctly by being moved from the root into an Organizational Unit within AWS Organizations. \| (main.py:226)
210 | 2020-03-11 11:22:12,857 \| ERROR \| __main__ \| 44444444444- Failed to update its base stack due to missing parameters (deployment_account_id or kms_arn), ensure this account has been bootstrapped correctly by being moved from the root into an Organizational Unit within AWS Organizations. \| (main.py:226)
```
I tried moving one account to root ou and back, but that resulted an error with Step Functions CreateOrUpdateBaseStack step:
```
{
  "account_id": "22222222222",
  "cross_account_access_role": "OrganizationAccountAccessRole",
  "deployment_account_id": "22222222222",
  "regions": [
    "eu-west-1",
    "us-east-1"
  ],
  "deployment_account_region": "eu-west-1",
  "moved_to_root": 0,
  "moved_to_protected": 0,
  "is_deployment_account": 0,
  "ou_name": "security",
  "full_path": "adf-bootstrap/security",
  "destination_ou_id": "ou-bar-1337asd",
  "source_ou_id": "r-foo",
  "deployment_account_parameters": {
    "organization_id": "o-foobar12",
    "master_account_id": "7777777777",
    "notification_endpoint": "adf-notifications",
    "notification_type": "lambda",
    "cross_account_access_role": "OrganizationAccountAccessRole",
    "deployment_account_bucket": "adf-shared-modules-eu-west-1-f9z2e9",
    "adf_version": "3.0.4",
    "adf_log_level": "INFO"
  },
  "error": {
    "Error": "GenericAccountConfigureError",
    "Cause": "{\"errorMessage\": \"An error occurred (ValidationError) when calling the CreateChangeSet operation: Unable to fetch parameters [organization_id] from parameter store for this account.\", \"errorType\": \"GenericAccountConfigureError\", \"stackTrace\": [\"  File \\\"/var/task/account_bootstrap.py\\\", line 122, in lambda_handler\\n    cloudformation.create_stack()\\n\", \"  File \\\"/opt/python/cloudformation.py\\\", line 277, in create_stack\\n    create_change_set = self._create_change_set()\\n\", \"  File \\\"/opt/python/cloudformation.py\\\", line 206, in _create_change_set\\n    raise GenericAccountConfigureError(error)\\n\"]}"
  }
}
```
Removing my changes made pipeline to succeed, but now we are unable to deploy resources to Virginia.

**Comment by bundyfx** [comment]
Looking into this one and testing it out this week. Thanks for reporting.

**Comment by hynynen** [comment]
Have you had time to take a look at this? We managed with one region earlier, but our ADF usage has expanded a lot and we would need the ability of deploying resources into multiple regions now. These is going to be a show stopper sooner or later.

I have installed ADF to at least four customer environments by now and this one instance is acting up like this. We have had no problems with multi-region setups anywhere else. I have also invested few days of my time investigating the code and trying things without success. I am clueless.

**Comment by sbkok** [comment]
Hi @hynynen,

I cannot seem to reproduce this issue that you are running into.
I've deployed this in a few ADF organizations and they onboard us-east-1 as an additional region just fine when adding the same patch as you described above.

It could be an access issue, could you check whether:
1. There might be an SCP configured, that blocks access in other regions?
1. The cross-organization-access-role has a boundary set or strict deny to other regions?

**Comment by sbkok** [comment]
I'm closing this issue as it has been inactive for a few weeks. This probably means that it is not reproducible or it has been fixed in the meanwhile.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/awslabs/aws-deployment-framework/releases). Thank you!
