### ISSUE TITLE
Upload function using s3-uri or s3-url fails

### ISSUE THREAD

**Issue by hynynen** [awslabs/aws-deployment-framework#299]
I have this parameters file global.yml
```
Parameters:
    FlowLogsRetention: '30'
    S3BucketFlowLogs: "someFLowLogsBucket"
    IPAMFunctionCode: upload:s3-url:ipam.zip
```
Mechanism is introduced here: https://github.com/awslabs/aws-deployment-framework/blob/master/docs/user-guide.md#uploading-assets

My pipeline fails at build stage:
```

[Container] 2020/10/21 13:46:24 Running command python adf-build/generate_params.py
--
22 | Traceback (most recent call last):
23 | File "adf-build/generate_params.py", line 166, in <module>
24 | main()
25 | File "adf-build/generate_params.py", line 162, in main
26 | parameters.create_parameter_files()
27 | File "adf-build/generate_params.py", line 88, in create_parameter_files
28 | compare_params
29 | File "adf-build/generate_params.py", line 148, in _param_updater
30 | self._determine_parameter_structure(comparison_parameters, resolver)
31 | File "adf-build/generate_params.py", line 135, in _determine_parameter_structure
32 | return self._determine_parameter_structure(value, resolver)
33 | File "adf-build/generate_params.py", line 136, in _determine_parameter_structure
34 | if self._determine_intrinsic_function(resolver, value, key):
35 | File "adf-build/generate_params.py", line 127, in _determine_intrinsic_function
36 | return resolver.upload(value, key, self.file_name)
37 | File "/codebuild/output/src590690604/src/adf-build/resolver.py", line 101, in upload
38 | ) from None
39 | Exception: When uploading to S3 you need to specify a pathing style for the response either path or virtual-hosted, read more: https://docs.aws.amazon.com/AmazonS3/latest/dev/VirtualHosting.html
```

**Comment by sbkok** [comment]
Hi Henry,

Apologies for the late reply. This issue will be fixed with the next release of ADF, v3.1.0.
It was fixed in PR: #275, but that fix is not released as a new ADF version yet.
I will keep this issue open until it is released officially.

Best regards, Simon
