### ISSUE TITLE
aws-deployment-framework-bootstrap-pipeline failed for v1.0.0. 

### ISSUE THREAD

**Issue by jing-1strategy** [awslabs/aws-deployment-framework#62]
After launching ADF via the Serverless Application Repository, stage "UploadAndUpdateBaseStacks" in pipeline "aws-deployment-framework-bootstrap-pipeline" failed, here is the log:
...
[Container] 2019/06/06 22:40:44 Running command python adf-build/main.py 
2019-06-06 22:40:44,925 | INFO | __main__ | ADF Version 1.0.0 | (main.py:206) 
2019-06-06 22:40:44,925 | INFO | __main__ | ADF Log Level is INFO | (main.py:207) 
2019-06-06 22:40:46,303 | INFO | organizations | SCPs are currently enabled within the Organization | (organizations.py:46) 
2019-06-06 22:41:08,880 | INFO | cloudformation | 355189840595 - Executing Cloudformation Change Set with name: adf-global-base-adf-build | (cloudformation.py:245) 
2019-06-06 22:41:09,071 | INFO | cloudformation | 355189840595 - Waiting for CloudFormation stack: adf-global-base-adf-build in us-west-2 to reach stack_create_complete | (cloudformation.py:130) 
2019-06-06 22:42:02,117 | INFO | cloudformation | 182360788898 - Executing Cloudformation Change Set with name: adf-regional-base-deployment | (cloudformation.py:245) 
2019-06-06 22:42:02,389 | INFO | cloudformation | 182360788898 - Waiting for CloudFormation stack: adf-regional-base-deployment in us-east-1 to reach stack_update_complete | (cloudformation.py:130) 
2019-06-06 22:44:47,921 | INFO | cloudformation | 182360788898 - Executing Cloudformation Change Set with name: adf-global-base-deployment | (cloudformation.py:245) 
2019-06-06 22:44:48,251 | INFO | cloudformation | 182360788898 - Waiting for CloudFormation stack: adf-global-base-deployment in us-west-2 to reach stack_update_complete | (cloudformation.py:130) 
2019-06-06 22:47:35,636 | WARNING | organizations | Account 486349564477 is not an Active AWS Account | (organizations.py:127) 
2019-06-06 22:47:35,766 | INFO | __main__ | 728858254016 Is in the Root of the Organization, it will be skipped. | (main.py:171) 
2019-06-06 22:47:36,198 | INFO | __main__ |  | (main.py:202) 
Traceback (most recent call last): 
  File "adf-build/main.py", line 315, in <module> 
    main() 
  File "adf-build/main.py", line 292, in main 
    thread.join() 
  File "/codebuild/output/src431224951/src/adf-build/shared/python/thread.py", line 30, in join 
    raise self.exc 
  File "/codebuild/output/src431224951/src/adf-build/shared/python/thread.py", line 22, in run 
    **self._kwargs 
  File "adf-build/main.py", line 199, in worker_thread 
    cloudformation.create_stack() 
  File "/codebuild/output/src431224951/src/adf-build/shared/python/cloudformation.py", line 256, in create_stack 
    create_change_set = self._create_change_set() 
  File "/codebuild/output/src431224951/src/adf-build/shared/python/cloudformation.py", line 194, in _create_change_set 
    ChangeSetType=self._get_change_set_type()) 
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call 
    return self._make_api_call(operation_name, kwargs) 
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 661, in _make_api_call 
    raise error_class(parsed_response, operation_name) 
botocore.exceptions.ClientError: An error occurred (ValidationError) when calling the CreateChangeSet operation: Unable to fetch parameters [deployment_account_id,kms_arn] from parameter store for this account. 
Exception ignored in: <module 'threading' from '/usr/local/lib/python3.7/threading.py'> 
Traceback (most recent call last): 
  File "/usr/local/lib/python3.7/threading.py", line 1281, in _shutdown 
    t.join() 
  File "/codebuild/output/src431224951/src/adf-build/shared/python/thread.py", line 30, in join 
    raise self.exc 
  File "/codebuild/output/src431224951/src/adf-build/shared/python/thread.py", line 22, in run 
    **self._kwargs 
  File "adf-build/main.py", line 199, in worker_thread 
    cloudformation.create_stack() 
  File "/codebuild/output/src431224951/src/adf-build/shared/python/cloudformation.py", line 256, in create_stack 
    create_change_set = self._create_change_set() 
  File "/codebuild/output/src431224951/src/adf-build/shared/python/cloudformation.py", line 194, in _create_change_set 
    ChangeSetType=self._get_change_set_type()) 
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call 
    return self._make_api_call(operation_name, kwargs) 
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 661, in _make_api_call 
    raise error_class(parsed_response, operation_name) 
botocore.exceptions.ClientError: An error occurred (ValidationError) when calling the CreateChangeSet operation: Unable to fetch parameters [kms_arn] from parameter store for this account. 
 
[Container] 2019/06/06 22:47:38 Command did not exit successfully python adf-build/main.py exit status 1 
[Container] 2019/06/06 22:47:38 Phase complete: BUILD State: FAILED 
[Container] 2019/06/06 22:47:38 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: python adf-build/main.py. Reason: exit status 1

**Comment by bundyfx** [comment]
Hi @jing-1strategy ,

**deployment_account_id** and **kms_arn** are the two parameters that are added to an account's Parameter Store when the account is bootstrapped by moving it into an Organizational Unit, Im guessing that the account that ADF is attempting to update a base stack on here has not yet been bootstrapped and therefore cannot have the base stack updated. I think we can do a better job with the error message here and also add in explanation about how ADF works with pre-existing accounts in organizational units. 

If you can identify the account in question you should be able to move it into the Organization Root and then move it into its desired OU in order for its base stack to be applied. During the Step Function execution it will add the required deployment_account_id and kms_arn parameters to the account in order for it to apply its base stack. Another option, If you want to skip over a whole OU and not have ADF attempt to create/update base stacks then you can also set its value in the protected section in adfconfig.yml.

let me know how you go and i'll add in a issue for v1.0.1 that will include better error handling around this scenario.

**Comment by bundyfx** [comment]
Closing this one for now - We will be adding more verbose error handling in 1.0.1 to ensure its clear about the state of an account and if it has been bootstrapped yet or not.
