### ISSUE TITLE
('Globals', "'Architectures' is not a supported property of 'Function'. Must be one of the following values - 

### ISSUE THREAD

**Issue by ChrisWilkes33** [awslabs/aws-deployment-framework#772]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The template.yml file in this repository has Architectures in the Globals section and that seems to not be supported.

### Expected Behavior

a successful build

### Current Behavior

I download a .zip of the 4.0.0 branch of this repo and when I try to do a SAM build on the template in the repository, I get the following error.
```
systemname:/directory/tree/aws-deployment-framework-4.0.0# sam build --template src/template.yml
Traceback (most recent call last):
  File "samtranslator/plugins/globals/globals_plugin.py", line 29, in on_before_transform_template
  File "samtranslator/plugins/globals/globals.py", line 98, in __init__
  File "samtranslator/plugins/globals/globals.py", line 204, in _parse
samtranslator.plugins.globals.globals.InvalidGlobalsSectionException: ('Globals', "'Architectures' is not a supported property of 'Function'. Must be one of the following values - ['Handler', 'Runtime', 'CodeUri', 'DeadLetterQueue', 'Description', 'MemorySize', 'Timeout', 'VpcConfig', 'Environment', 'Tags', 'Tracing', 'KmsKeyArn', 'AutoPublishAlias', 'Layers', 'DeploymentPreference', 'PermissionsBoundary', 'ReservedConcurrentExecutions', 'ProvisionedConcurrencyConfig', 'AssumeRolePolicyDocument', 'EventInvokeConfig', 'FileSystemConfigs', 'CodeSigningConfigArn']")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "samcli/lib/samlib/wrapper.py", line 78, in run_plugins
  File "samcli/lib/samlib/wrapper.py", line 133, in parse
  File "samtranslator/plugins/__init__.py", line 136, in act
  File "samtranslator/plugins/__init__.py", line 133, in act
  File "samtranslator/plugins/globals/globals_plugin.py", line 31, in on_before_transform_template
samtranslator.model.exceptions.InvalidDocumentException: [InvalidGlobalsSectionException('Globals', "'Architectures' is not a supported property of 'Function'. Must be one of the following values - ['Handler', 'Runtime', 'CodeUri', 'DeadLetterQueue', 'Description', 'MemorySize', 'Timeout', 'VpcConfig', 'Environment', 'Tags', 'Tracing', 'KmsKeyArn', 'AutoPublishAlias', 'Layers', 'DeploymentPreference', 'PermissionsBoundary', 'ReservedConcurrentExecutions', 'ProvisionedConcurrencyConfig', 'AssumeRolePolicyDocument', 'EventInvokeConfig', 'FileSystemConfigs', 'CodeSigningConfigArn']")]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "samcli/__main__.py", line 12, in <module>
  File "click/core.py", line 829, in __call__
  File "click/core.py", line 782, in main
  File "click/core.py", line 1259, in invoke
  File "click/core.py", line 1066, in invoke
  File "click/core.py", line 610, in invoke
  File "click/decorators.py", line 73, in new_func
  File "click/core.py", line 610, in invoke
  File "samcli/lib/telemetry/metric.py", line 153, in wrapped
  File "samcli/lib/telemetry/metric.py", line 122, in wrapped
  File "samcli/lib/utils/version_checker.py", line 42, in wrapped
  File "samcli/cli/main.py", line 90, in wrapper
  File "samcli/commands/build/command.py", line 228, in cli
  File "samcli/commands/build/command.py", line 296, in do_cli
  File "samcli/commands/build/build_context.py", line 87, in __enter__
  File "samcli/lib/providers/sam_stack_provider.py", line 237, in get_stacks
  File "samcli/lib/providers/sam_stack_provider.py", line 53, in __init__
  File "samcli/lib/providers/sam_base_provider.py", line 189, in get_template
  File "samcli/lib/samlib/wrapper.py", line 82, in run_plugins
samcli.commands.validate.lib.exceptions.InvalidSamDocumentException: [InvalidGlobalsSectionException('Globals', "'Architectures' is not a supported property of 'Function'. Must be one of the following values - ['Handler', 'Runtime', 'CodeUri', 'DeadLetterQueue', 'Description', 'MemorySize', 'Timeout', 'VpcConfig', 'Environment', 'Tags', 'Tracing', 'KmsKeyArn', 'AutoPublishAlias', 'Layers', 'DeploymentPreference', 'PermissionsBoundary', 'ReservedConcurrentExecutions', 'ProvisionedConcurrencyConfig', 'AssumeRolePolicyDocument', 'EventInvokeConfig', 'FileSystemConfigs', 'CodeSigningConfigArn']")] ('Globals', "'Architectures' is not a supported property of 'Function'. Must be one of the following values - ['Handler', 'Runtime', 'CodeUri', 'DeadLetterQueue', 'Description', 'MemorySize', 'Timeout', 'VpcConfig', 'Environment', 'Tags', 'Tracing', 'KmsKeyArn', 'AutoPublishAlias', 'Layers', 'DeploymentPreference', 'PermissionsBoundary', 'ReservedConcurrentExecutions', 'ProvisionedConcurrencyConfig', 'AssumeRolePolicyDocument', 'EventInvokeConfig', 'FileSystemConfigs', 'CodeSigningConfigArn']")
[2296] Failed to execute script __main__
```

### Steps To Reproduce

1. Download .zip file of 4.0.0 tagged branch of this repository
2. Extract contents
3. Change into unzipped directory
4. run sam build --template src/template.yml
5. observer error

### Possible Solution

Potentially update the template

### ADF Version

4.0.0

### Contributing a fix?

- [ ] Yes, I am working on a fix to resolve this issue

**Comment by ChrisWilkes33** [comment]
Incidentally, when I try to do the same with the 3.2.1 branch it tells me that function needs architectures...

```
aws-deployment-framework-3.2.1# sam build --template src/template.yml
Traceback (most recent call last):
  File "samcli/lib/samlib/wrapper.py", line 78, in run_plugins
  File "samcli/lib/samlib/wrapper.py", line 147, in parse
samtranslator.model.exceptions.InvalidDocumentException: [InvalidResourceException('AccountFileProcessingFunction', 'property Architectures not defined for resource of type AWS::Serverless::Function'), InvalidResourceException('AccountAliasConfigFunction', 'property Architectures not defined for resource of type AWS::Serverless::Function'), InvalidResourceException('AccountTagConfigFunction', 'property Architectures not defined for resource of type AWS::Serverless::Function'), InvalidResourceException('AccountOUConfigFunction', 'property Architectures not defined for resource of type AWS::Serverless::Function'), InvalidResourceException('GetAccountRegionsFunction', 'property Architectures not defined for resource of type AWS::Serverless::Function'), InvalidResourceException('DeleteDefaultVPCFunction', 'property Architectures not defined for resource of type AWS::Serverless::Function'), InvalidResourceException('CreateAccountFunction', 'property Architectures not defined for resource of type AWS::Serverless::Function'), InvalidResourceException('RegisterAccountForSupportFunction', 'property Architectures not defined for resource of type AWS::Serverless::Function')]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "samcli/__main__.py", line 12, in <module>
  File "click/core.py", line 829, in __call__
  File "click/core.py", line 782, in main
  File "click/core.py", line 1259, in invoke
  File "click/core.py", line 1066, in invoke
  File "click/core.py", line 610, in invoke
  File "click/decorators.py", line 73, in new_func
  File "click/core.py", line 610, in invoke
  File "samcli/lib/telemetry/metric.py", line 153, in wrapped
  File "samcli/lib/telemetry/metric.py", line 122, in wrapped
  File "samcli/lib/utils/version_checker.py", line 42, in wrapped
  File "samcli/cli/main.py", line 90, in wrapper
  File "samcli/commands/build/command.py", line 228, in cli
  File "samcli/commands/build/command.py", line 296, in do_cli
  File "samcli/commands/build/build_context.py", line 87, in __enter__
  File "samcli/lib/providers/sam_stack_provider.py", line 237, in get_stacks
  File "samcli/lib/providers/sam_stack_provider.py", line 53, in __init__
  File "samcli/lib/providers/sam_base_provider.py", line 189, in get_template
  File "samcli/lib/samlib/wrapper.py", line 82, in run_plugins
samcli.commands.validate.lib.exceptions.InvalidSamDocumentException: [InvalidResourceException('AccountFileProcessingFunction', 'property Architectures not defined for resource of type AWS::Serverless::Function'), InvalidResourceException('AccountAliasConfigFunction', 'property Architectures not defined for resource of type AWS::Serverless::Function'), InvalidResourceException('AccountTagConfigFunction', 'property Architectures not defined for resource of type AWS::Serverless::Function'), InvalidResourceException('AccountOUConfigFunction', 'property Architectures not defined for resource of type AWS::Serverless::Function'), InvalidResourceException('GetAccountRegionsFunction', 'property Architectures not defined for resource of type AWS::Serverless::Function'), InvalidResourceException('DeleteDefaultVPCFunction', 'property Architectures not defined for resource of type AWS::Serverless::Function'), InvalidResourceException('CreateAccountFunction', 'property Architectures not defined for resource of type AWS::Serverless::Function'), InvalidResourceException('RegisterAccountForSupportFunction', 'property Architectures not defined for resource of type AWS::Serverless::Function')] ('AccountAliasConfigFunction', 'property Architectures not defined for resource of type AWS::Serverless::Function') ('AccountFileProcessingFunction', 'property Architectures not defined for resource of type AWS::Serverless::Function') ('AccountOUConfigFunction', 'property Architectures not defined for resource of type AWS::Serverless::Function') ('AccountTagConfigFunction', 'property Architectures not defined for resource of type AWS::Serverless::Function') ('CreateAccountFunction', 'property Architectures not defined for resource of type AWS::Serverless::Function') ('DeleteDefaultVPCFunction', 'property Architectures not defined for resource of type AWS::Serverless::Function') ('GetAccountRegionsFunction', 'property Architectures not defined for resource of type AWS::Serverless::Function') ('RegisterAccountForSupportFunction', 'property Architectures not defined for resource of type AWS::Serverless::Function')
[7013] Failed to execute script __main__
```

**Comment by ChrisWilkes33** [comment]
I also should pass on that this is in an air-gapped environment with no actual connection out to on the system I am building on.

**Comment by ChrisWilkes33** [comment]
This issue was the result of an outdated sam cli being used.
